import java.util.ArrayList;

/**
 * Fibonacci numbers
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 */


public class FibonacciNumbers {
    public static void main(String[] args) {
        ArrayList<Integer> arrayList;
        int lastNumber = 4000000;
        int firstNumber = 1;
        int secondNumber = 2;
        arrayList = fillArray(lastNumber, firstNumber, secondNumber);
        printList(arrayList);
        System.out.println();
        arrayList = allEvenValue(arrayList);
        printList(arrayList);
        System.out.println();
        findSumOfAllElem(arrayList);
    }

    public static ArrayList<Integer> fillArray(int lastValue, int firstValue, int secondValue) {
        ArrayList<Integer> fillList = new ArrayList<Integer>();
        int tempValue = 0;
        while (tempValue < lastValue) {
            fillList.add(firstValue);
            tempValue = secondValue;
            secondValue = firstValue + secondValue;
            firstValue = tempValue;
        }
        return fillList;
    }

    public static ArrayList<Integer> allEvenValue(ArrayList<Integer> tempList) {
        ArrayList<Integer> evenValuesList = new ArrayList<Integer>();
        for (int i = 0; i < tempList.size(); i++) {
            if (tempList.get(i) % 2 == 0) {
                evenValuesList.add(tempList.get(i));
            }
        }
        return evenValuesList;
    }

    public static void printList(ArrayList tempList) {
        for (int i = 0; i < tempList.size(); i++) {
            System.out.print(tempList.get(i) + " ");
        }
    }

    public static void findSumOfAllElem(ArrayList<Integer> tempList) {
        int sumOfEl = 0;
        for (int i = 0; i < tempList.size(); i++) {
            sumOfEl = tempList.get(i) + sumOfEl;
        }
        System.out.println("Sum of all elements= " + sumOfEl);
    }
}
